### ISSUE TITLE
 raise ImportError, "Unknown magic number %s in %s" % (ord(magic[0])+256*ord(magic[1]), filename)

### ISSUE THREAD

**Issue by loveshell** [wibiti/uncompyle2#19]
root@t:~/wibiti-uncompyle2-5f4ddc2# uncompyle2 -o /tmp/ aa.pyc 
#2012.09.07 07:44:02 CST
### Can't uncompyle aa.pyc

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/uncompyle2/**init**.py", line 191, in main
    uncompyle_file(infile, outstream, showasm, showast)
  File "/usr/local/lib/python2.7/site-packages/uncompyle2/**init**.py", line 127, in uncompyle_file
    version, co = _load_module(filename)
  File "/usr/local/lib/python2.7/site-packages/uncompyle2/__init__.py", line 72, in _load_module
    raise ImportError, "Unknown magic number %s in %s" % (ord(magic[0])+256*ord(magic[1]), filename)
ImportError: Unknown magic number 99 in aa.pyc
# decompiled 0 files: 0 okay, 1 failed, 0 verify failed
#2012.09.07 07:44:02 CST

**Comment by darkr4y** [comment]
@loveshell also have the same problem , can you help me?

**Comment by PandaTea** [comment]
@loveshell how?!QAQ?!!!
