### ISSUE TITLE
cannot import name main

### ISSUE THREAD

**Issue by fermion42** [wibiti/uncompyle2#34]
Traceback (most recent call last):
  File "D:\Python27\Scripts\uncompyle2", line 55, in <module>
    from uncompyle2 import main, verify
  File "D:\Python27\Scripts\uncompyle2.py", line 55, in <module>
    from uncompyle2 import main, verify
ImportError: cannot import name main

**Comment by p41632ll0n9** [comment]
I got the same issue on my Debian Linux. 
How can I solve this issue? 

Traceback (most recent call last):
  File "./scripts/uncompyle2", line 55, in <module>
    from uncompyle2 import main, verify
ImportError: No module named uncompyle2

**Comment by petercat23** [comment]
any solution for this?

**Comment by thatosmk** [comment]
also getting this error, anyone?

**Comment by wibiti** [comment]
There shouldn't be an uncompyle2.py file in the Scripts dir.
